# -*- coding: utf-8 -*-
"""Série temporal com Facebook Prophet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FUO7FzXCpRIlYlwl9xI80NPKC-6TQVHp

# Série temporal com Facebook Prophet - previsão de visualizações diárias de páginas web

## Instalação da biblioteca e importação da base de dados

- Visualizações diárias de uma página web da Wikipedia: https://en.wikipedia.org/wiki/Peyton_Manning
"""

!pip install fbprophet

from fbprophet import Prophet
import pandas as pd

dataset = pd.read_csv('/content/page_wikipedia.csv')
dataset

dataset.describe()

dataset.hist();

dataset = dataset[['date', 'views']].rename(columns = {'date': 'ds', 'views': 'y'})
dataset

dataset = dataset.sort_values(by = 'ds')
dataset

"""## Construção do modelo e previsões"""

model = Prophet()
model.fit(dataset)

future = model.make_future_dataframe(periods=90)
forecast = model.predict(future)

forecast.head()

len(dataset), len(forecast)

len(forecast) - len(dataset)

forecast.tail(90)

"""## Gráfico das previsões"""

model.plot(forecast, xlabel = 'Date', ylabel = 'Views');

model.plot_components(forecast);

from fbprophet.plot import plot_plotly, plot_components_plotly

plot_plotly(model, forecast)

plot_components_plotly(model, forecast)