# -*- coding: utf-8 -*-
"""Operadores lógicos e relacionais.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tI457d3VjWIPXWF5ysGyja2GQq9yQ5Nd

# Operadores lógicos e relacionais

## Operadores lógicos
"""

a = True
b = False

print(a, b)

a and b

a & b

c = a and b
print("'A' e 'B' são iguais é", c)

a or b

a | b

d = a or b
print("'A' ou 'B' é igual a", d)

not a

not b

"""## Operadores relacionais"""

5 > 3

5 < 3

5 >= 5

5 <= 3

5 == 3

5 != 3