# -*- coding: utf-8 -*-
"""Python Exercícios Coleções.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BLBCSYFl9vcmnzWCcH2t0-gsk9J85Qie

# Exercício 1 - listas

Crie uma estrutura de repetição para fazer a leitura de 5 números inteiros e os armazene dentro de uma lista. Após a leitura, crie outra estrutura de repetição para somar todos os valores digitados
"""

lista = []
for _ in range(1, 6):
  valor = int(input('Digite o valor: '))
  lista.append(valor)

lista

len(lista)

soma = 0
for i in range(len(lista)):
  #print(lista[i])
  soma += lista[i]
print('Soma: ', soma)

lista.sum()

import numpy as np
np.array(lista).sum()

"""# Exercícios 2 - dicionários

Crie um dicionário para armazenar o nome e a nota de 3 alunos, fazendo a leitura dos valores por meio de uma estrutura de repetição. Depois, crie uma nova estrutura de repetição para somar todas as notas e retornar a média
"""

alunos = {}
for _ in range(1, 4):
  nome = input('Digite o nome: ')
  nota = float(input('Digite a nota: '))
  alunos[nome] = nota

alunos

alunos['maria']

alunos.values()

soma = 0
for nota in alunos.values():
  #print(nota)
  soma += nota
print('Média: ', soma / 3)

"""# Exercício 3: Matriz

Dada a matriz abaixo, construa uma estrutura de repetição para percorrer e somar todos os elementos da matriz
"""

matriz = np.array([[3, 4, 1],
                   [3, 1, 5]])
matriz

matriz.shape

soma = 0
for i in range(matriz.shape[0]):
  for j in range(matriz.shape[1]):
    #print(matriz[i][j])
    soma += matriz[i][j]
print('Soma: ', soma)