# -*- coding: utf-8 -*-
"""Módulos úteis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13lChRgM0FhHkcFsuY4UVuL1m9yo_UMId

# Módulos úteis

## Biblioteca math

https://docs.python.org/3/library/math.html
"""

import math

math.sqrt(9)

math.sin(45)

math.cos(45)

math.log(1000, 10)

math.log(32, 2)

math.log(1000)

math.e

math.pi

"""## Biblioteca datetime

https://docs.python.org/3/library/datetime.html
"""

import datetime

dir(datetime)

datetime.date.today()

datetime.datetime.now()

data = datetime.date(2020, 7, 10)

data

data.day

data.month

data.year

horario = datetime.datetime(2020, 7, 10, 7, 30, 0)

horario

horario.hour

horario.minute

horario.second

"""## Biblioteca random

https://docs.python.org/3/library/random.html
"""

import random

random.random()

random.randint(1,10)

random.randrange(0, 10, 2)

random.randrange(0, 10, 3)

x = ['K', 'd', 13, '34-j', 'x']
x

random.choice(x)

"""## Biblioteca time

https://docs.python.org/3/library/time.html
"""

import time as tm

tm.time()

antes = tm.time()
lista = []
for i in range(0,10000):
  lista.append(i)
depois = tm.time()

intervalo = depois - antes
print(f'Tempo: {intervalo} segundos')

print('Finalizando...')
tm.sleep(2)
print('...')
tm.sleep(2)
print('Até a próxima')