# -*- coding: utf-8 -*-
"""Python Exercício Módulos personalizados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E6lIsva6SY19XpIZoaLmxfUUTlyNQGSB

# Exercício 1

Crie um arquivo .py com duas funções
- Função para ler um string (recebe como parâmetro uma mensagem e retorna o que o usuário digitou)
- Função para ler um número float (recebe como parâmetro uma mensagem e retorna o que o usuário digitou)

Importar o arquivo criado no Google Colab e testar as funções
"""

import leitura as lt

texto = lt.ler_string('Digite o seu nome: ')
print(texto)

carro = lt.ler_string('Digite o nome do seu carro: ')
print(carro)

numero = lt.ler_float('Digite o valor 1: ')
print(numero)

numero2 = lt.ler_float('Digite o valor 2: ')
print(numero2)