# -*- coding: utf-8 -*-
"""Tratamento de erros e exceções.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RXg74NnNEQ5pLJRLSV7Qu1TLYcs6Cd0H

# Tratamento de erros e exceções

- NameError: variável nao foi definida
- TypeError: tipos de dados incompatíveis
- RuntimeError: erro de execução
- SyntaxError: sintaxe digitada é inválida e não reconhecida pelo interpretador
- ZeroDivisionError: divisão por zero
- IndexError: índice está fora da coleção

## Tipos de erros
"""

3 = 4

print('Meu nome é', nome)

print(3 / 0)

2.3 / 'cachorro'

c = [1,2,3,4,5]
c

c[5]

"""## Tratamento de erros"""

try:
  n = int(input('Digite um número inteiro: '))
except:
  print('Valor inválido')
else:
  print(f'Valor digitado é {n}')

while True:
  try:
    n = int(input('Digite um número inteiro: '))
  except:
    print('Valor inválido')
  else:
    print(f'Valor digitado é {n}')
    break

while True:
  try:
    p = int(input('Digite um número inteiro'))
  except ValueError:
    print('Valor inválido')
  except KeyboardInterrupt:
    print('Usuário interrompeu a execução')
    break
  else:
    print(f'Valor digitado é {p}')
    break