# -*- coding: utf-8 -*-
"""Manipulação de arquivos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rVUjsFJko0wOMKhpzdf-oqLdN-RDKqMv

# Manipulação de arquivos
"""

with open('/content/frase1.txt', 'r') as tex:
  for linha in tex:
    print(linha)

with open('/content/frase1.txt') as tex:
  r = tex.readlines()

r

with open('texto2.txt', 'w') as texto:
  texto.write('Olá a todos')

with open('texto2.txt', 'r') as tex:
  for linha in tex:
    print(linha)