# -*- coding: utf-8 -*-
"""Exercícios Manipulação de arquivos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tplgyt0g8nEvvEq0XREKFtbhoJ0PaVYw

# Exercício

Considerando o dicionário com o nome dos alunos e suas respectivas notas, crie uma estrutura de repetição para percorrer cada elemento do dicionário para gravar cada aluno em um novo arquivo de texto
- Cada aluno deve ocupar uma linha do novo arquivo de texto
- O formato deve ser: nome,nota (Pedro,8.0)
- Após a criação do arquivo de texto, faça a leitura do arquivo e mostre todos os alunos
"""

alunos = {'Pedro': 8.0, 'Maria': 10.0, 'Amilton': 7.5}
alunos

with open('alunos.txt', 'w') as arquivo:
  for aluno, nota in alunos.items():
    arquivo.write(f'{aluno},{nota}\n')

with open('alunos.txt', 'r') as arquivo:
  for linha in arquivo:
    print(linha)