# -*- coding: utf-8 -*-
"""Exercício Expressões Regulares.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u0uIV97CQ5ASMk25tkeBbO4Yywdyb66a

# Exercícios

Crie expressões regulares para extrair as seguintes informações do texto abaixo (use a função findall):
- Números
- CEPs
- URLs
"""

texto = "Minha casa fica na rua Carneiro, 78. O CEP é 88388-000 e 11111-111 meu site é https://www.iaexpert.academy http://iaexpert.com.br"

import re
re.findall('\d', texto)

re.findall('\d{5}-\d{3}', texto)

re.findall('https?://[A-Za-z0-9./]+', texto)