# -*- coding: utf-8 -*-
"""Python Exercício Orientação a Objetos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1evQmxCHrO7p2Oujx49hn3OhcSsDwvQ9b

# Exercício 1

Crie uma classe chamada aluno com os seguintes atributos:

- Nome
- Nota 1
- Nota 2
- Crie um construtor para a classe (__init__)

Crie as seguintes funções (métodos):

- Calcula média, retornando a média aritmética entre as notas
- Mostra dados, que somente imprime o valor de todos os atributos
- Resultado, que verifica se o aluno está aprovado ou reprovado (se a média for maior ou igual a 6.0, o aluno está aprovado)

Crie dois objetos (aluno1 e aluno2) e teste as funções
"""

class Aluno:
  def __init__(self, nome, nota1, nota2):
    self.nome = nome
    self.nota1 = nota1
    self.nota2 = nota2
    self.media = 0.0
   
  def calcula_media(self):
    self.media = (self.nota1 + self.nota2) / 2
    return self.media

  def mostra_dados(self):
    print('Nome: ', self.nome)
    print('Nota 1:', self.nota1)
    print('Nota 2:', self.nota2)
    print('Média:', self.media)
  
  def resultado(self):
    if self.media >= 6.0:
      print('Aprovado')
    else:
      print('Reprovado')

aluno1 = Aluno('Pedro', 7.0, 9.0)
media = aluno1.calcula_media()
print(media)

aluno1.mostra_dados()

aluno1.resultado()

aluno2 = Aluno('João', 7.0, 2.0)
media = aluno2.calcula_media()
aluno2.mostra_dados()
aluno2.resultado()